selected_categories:
  - Cap On Liability
  - Audit Rights
  - Termination For Convenience
  - Exclusivity
  - Renewal Term
  - Change Of Control
  - Uncapped Liability
  - Notice Period To Terminate Renewal